### PR TITLE
Add /topic/ Endpoint

### PR DESCRIPTION
**Pull request by davidswarbrick**
- Added /topic/<topic> url to group email templates by topic, for specific campaigns/ideas
- Removed BLM logo to generalise project to multiple campaigns
- Added 3 email templates
- Reformatted HTML to use EmailTemplate object
- HTML templates inherit from a "results.html" page, with different titles for per-topic and all topic results
- Results page includes urls for "more info" and attribution for the template creator
- Results page now uses **target name** and **template name** (rather than target email address and subject line) : this can be altered if the old layout was preferred, but should be addressed before merging.
- Used new branching layout feature/<name> and the develop branch for staging (although I apologise for the multiple merges and messy log)

### CODE REVIEW

**Comment by rafeeJ** [comment]
Are you going to add a template for a database miss? Currently it’s just a JSON 404

**Comment by davidswarbrick** [comment]
> Are you going to add a template for a database miss? Currently it’s just a JSON 404

Yes this needs to be handled properly but I'm not familiar with the best way to do so in Flask, @behradkoohy can you advise?

**Comment by davidswarbrick** [comment]
From [the flask documentation](https://flask.palletsprojects.com/en/1.1.x/api/?highlight=abort#flask.abort) we could implement `abort(404)` for now ?

**Comment by rafeeJ** [comment]
Thanks for the change @fpervaiz, anyway we could have a button on the 404 page so user can redirect back to home page?  That would be the perfect

**Comment by davidswarbrick** [comment]
Thanks for your additions @fpervaiz ! @rafeeJ the header on the 404 page includes a link to the homepage, so I will go ahead and merge.

**Pull request merged**
