### PR TITLE
Update Secretary of State for Education's email

### PR DESCRIPTION
**Pull request by ImTomEddy**
Updated the contact email for Secretary of State for Education (Gavin Williamson).
Re-Enabled the email to Secretary of State for Education RE: Black Histories

### CODE REVIEW

**Comment by ImTomEddy** [comment]
Hi,

This is the response I got when testing the email on the 11th of June at just before 10 pm.

```
This email box is not being monitored between 5pm and 9am. 
If your email is urgent please forward it to the duty Private Secretaries at the following emails: 
Warwick.Sharp@education.gov.uk
Juliette.Cammaerts@education.gov.uk
Otherwise your email will be picked up in the morning.
```

I'm guessing it might be different depending on time, but there's nothing redirecting you towards the online contact form.

**Comment by rafeeJ** [comment]
Thanks for this! I’m currently investigating a pdf that contains direct emails for each department which make up the cabinet. Currently writing a script to scrape and publish to our production db.

**Comment by ImTomEddy** [comment]
> Thanks for this! I’m currently investigating a pdf that contains direct emails for each department which make up the cabinet. Currently writing a script to scrape and publish to our production db.
> 
> It’s in branch: feature/cabinet-script

Great stuff! I would contribute, but my python knowledge is awful 😞 This site might also help https://ceoemail.com/uk-government-email.php - but you'll have to grab the emails manually.

If you see an email with a domain containing `gsi` it's worth testing with and without the gsi because it is being phased out (https://www.gov.uk/government/publications/changing-government-email-migrating-from-gsi/changing-government-email-migrating-from-gsi).

**Comment by rafeeJ** [comment]
Thanks for this comment. I’m going to close this PR since I have updated our database with information of the cabinet and their direct emails. Thanks for bringing this up though!!

If you have any questions or want to still contribute, you can message me on Discord: Rafee#8153

Cheers!

**Comment by davidswarbrick** [comment]
This needs to be reopened as the initial request has not been addressed.

**Comment by davidswarbrick** [comment]
Ah it seems this isn’t possible due to branch deletion, since the new email seems to get through we’ll discuss whether it’s appropriate to send the template to the new location (as it would be at odds with the auto response from the other inbox) and address in a future PR.

**Pull request closed without merging**
